name: 'Update pull requests'
description: 'Updates the pull request branch with the latest upstream changes by merging HEAD from the base branch into the pull request branch'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'green'
  icon: 'arrow-down-left'